# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import voice_pb2 as voice__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in voice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/tsbot.voice.v1.VoiceService/Ping',
                request_serializer=voice__pb2.Empty.SerializeToString,
                response_deserializer=voice__pb2.PingResponse.FromString,
                _registered_method=True)
        self.Play = channel.unary_unary(
                '/tsbot.voice.v1.VoiceService/Play',
                request_serializer=voice__pb2.PlayRequest.SerializeToString,
                response_deserializer=voice__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/tsbot.voice.v1.VoiceService/Pause',
                request_serializer=voice__pb2.Empty.SerializeToString,
                response_deserializer=voice__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/tsbot.voice.v1.VoiceService/Resume',
                request_serializer=voice__pb2.Empty.SerializeToString,
                response_deserializer=voice__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/tsbot.voice.v1.VoiceService/Stop',
                request_serializer=voice__pb2.Empty.SerializeToString,
                response_deserializer=voice__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.Skip = channel.unary_unary(
                '/tsbot.voice.v1.VoiceService/Skip',
                request_serializer=voice__pb2.Empty.SerializeToString,
                response_deserializer=voice__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.SendNotice = channel.unary_unary(
                '/tsbot.voice.v1.VoiceService/SendNotice',
                request_serializer=voice__pb2.NoticeRequest.SerializeToString,
                response_deserializer=voice__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.SetVolume = channel.unary_unary(
                '/tsbot.voice.v1.VoiceService/SetVolume',
                request_serializer=voice__pb2.SetVolumeRequest.SerializeToString,
                response_deserializer=voice__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/tsbot.voice.v1.VoiceService/GetStatus',
                request_serializer=voice__pb2.Empty.SerializeToString,
                response_deserializer=voice__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/tsbot.voice.v1.VoiceService/SubscribeEvents',
                request_serializer=voice__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=voice__pb2.Event.FromString,
                _registered_method=True)


class VoiceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Play(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Skip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendNotice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=voice__pb2.Empty.FromString,
                    response_serializer=voice__pb2.PingResponse.SerializeToString,
            ),
            'Play': grpc.unary_unary_rpc_method_handler(
                    servicer.Play,
                    request_deserializer=voice__pb2.PlayRequest.FromString,
                    response_serializer=voice__pb2.CommandResponse.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=voice__pb2.Empty.FromString,
                    response_serializer=voice__pb2.CommandResponse.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=voice__pb2.Empty.FromString,
                    response_serializer=voice__pb2.CommandResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=voice__pb2.Empty.FromString,
                    response_serializer=voice__pb2.CommandResponse.SerializeToString,
            ),
            'Skip': grpc.unary_unary_rpc_method_handler(
                    servicer.Skip,
                    request_deserializer=voice__pb2.Empty.FromString,
                    response_serializer=voice__pb2.CommandResponse.SerializeToString,
            ),
            'SendNotice': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNotice,
                    request_deserializer=voice__pb2.NoticeRequest.FromString,
                    response_serializer=voice__pb2.CommandResponse.SerializeToString,
            ),
            'SetVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVolume,
                    request_deserializer=voice__pb2.SetVolumeRequest.FromString,
                    response_serializer=voice__pb2.CommandResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=voice__pb2.Empty.FromString,
                    response_serializer=voice__pb2.StatusResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=voice__pb2.SubscribeRequest.FromString,
                    response_serializer=voice__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tsbot.voice.v1.VoiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tsbot.voice.v1.VoiceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsbot.voice.v1.VoiceService/Ping',
            voice__pb2.Empty.SerializeToString,
            voice__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Play(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsbot.voice.v1.VoiceService/Play',
            voice__pb2.PlayRequest.SerializeToString,
            voice__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsbot.voice.v1.VoiceService/Pause',
            voice__pb2.Empty.SerializeToString,
            voice__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsbot.voice.v1.VoiceService/Resume',
            voice__pb2.Empty.SerializeToString,
            voice__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsbot.voice.v1.VoiceService/Stop',
            voice__pb2.Empty.SerializeToString,
            voice__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Skip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsbot.voice.v1.VoiceService/Skip',
            voice__pb2.Empty.SerializeToString,
            voice__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendNotice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsbot.voice.v1.VoiceService/SendNotice',
            voice__pb2.NoticeRequest.SerializeToString,
            voice__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsbot.voice.v1.VoiceService/SetVolume',
            voice__pb2.SetVolumeRequest.SerializeToString,
            voice__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsbot.voice.v1.VoiceService/GetStatus',
            voice__pb2.Empty.SerializeToString,
            voice__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tsbot.voice.v1.VoiceService/SubscribeEvents',
            voice__pb2.SubscribeRequest.SerializeToString,
            voice__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
